version: 2

sources:
  - name: raw_data
    description: "Raw data for taxi rides in New York City"
    database: taxi_rides_ny
    schema: prod
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
      
